[package]
name = "env_encryption_tool"
version = "0.9.6"
edition = "2024"

[dependencies]
rand_core = { version = "0.9.3", features = ["os_rng"] } # Random number generators and other randomness functionality. 
argon2 = "0.5.3"                                         # Key derivation with resistance to GPU cracking and side-channel attacks
log = "0.4.27"                                           # A lightweight logging facade for Rust 
aes-gcm = "0.10.3"                                       # AES-GCM (Galois/Counter Mode) Authenticated Encryption with Associated Data (AEAD) Cipher
env = "1.0.1"                                            # Provides a safe interface for std::env::{set_var, remove_var}.
once_cell = "1.21.3"                                     # Single assignment cells and lazy values.
