[package]
name = "env_encryption_tool"
version = "0.9.2"
edition = "2021"

[dependencies]
rand_core = { version = "0.9.0", features = ["os_rng"] } # Random number generators and other randomness functionality. 
argon2 = "0.5.3"                                         # Key derivation with resistance to GPU cracking and side-channel attacks
log = "0.4.25"                                           # A lightweight logging facade for Rust 
aes-gcm = "0.10.3"                                       # AES-GCM (Galois/Counter Mode) Authenticated Encryption with Associated Data (AEAD) Cipher
